apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deploy
  namespace: vlku3
spec:
  selector:
    matchLabels:
      app: audit-app
  template:
    metadata:
      labels:
        app: audit-app
    spec:
      containers:
      - name: audit-app
        image: registry.apps.k8s.ose-prod.solution.sbt/vlku/audit-app:0.8
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /config
          name: audit
        securityContext:     ---> this will allow pod to make changes on the Host directory
          privileged: true 
      volumes:
      - name: audit
        hostPath:
          path: /etc/kubernetes/manifests/
      tolerations:
        - effect: NoExecute
          operator: Exists
      nodeName: master-03.k8s.r4c-test.solution.sbt

       
  

