apiVersion: apps/v1
kind: Deployment
metadata:
  name: audit-deploy
spec:
  selector:
    matchLabels:
      app: audit-app
  template:
    metadata:
      labels:
        app: audit-app
    spec:
      containers:
      - name: audit-app
        image: registry.apps.k8s.ose-prod.solution.sbt/vlku/audit-app:0.4
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /config
          name: audit
      volumes:
      - name: audit
        hostPath:
          path: /etc/kubernetes/manifests/
      tolerations:
        - effect: NoExecute
          operator: Exists
      nodeName: master-03.k8s.r4c-test.solution.sbt
       
  

